### ISSUE TITLE
Packer fails to complete using windows_2019_docker.json (parallels)

### ISSUE THREAD

**Issue by shaunhp** [StefanScherer/packer-windows#262]
Hi Stefan,

I'm following along with the intention of using your other project `windows-docker-machine`.

My environment is using docker machine for Mac, Parallels and Vagrant.

After installing Parallels, and installing the `docker-machine-parallels`, and then installing vagrant and adding the `vagrant-parallels` plugin, I began to use your script to build a Windows 2019 docker image: 
`packer build --only=parallels-iso windows_2019_docker.json`

It starts to build ok, everything is looking good, the machine is created, begins the patching cycle and installs the parallels tools etc, but then gets stuck.  The last output I see from the build is this:

```
parallels-iso: Extracting archive: C:\Windows\Temp\prl-tools-win.iso
    parallels-iso:
    parallels-iso: WARNINGS:
    parallels-iso: There are data after the end of archive
    parallels-iso:
    parallels-iso: --
    parallels-iso: Path = C:\Windows\Temp\prl-tools-win.iso
    parallels-iso: Type = Iso
    parallels-iso: WARNINGS:
    parallels-iso: There are data after the end of archive
    parallels-iso: Physical Size = 10440704
    parallels-iso: Tail Size = 8192
    parallels-iso: Created = 2020-04-13 07:01:10
    parallels-iso: Modified = 2020-04-13 07:01:10
    parallels-iso:
    parallels-iso: Everything is Ok
    parallels-iso:
    parallels-iso: Archives with Warnings: 1
    parallels-iso:
    parallels-iso: Warnings: 1
    parallels-iso: Folders: 7
    parallels-iso: Files: 12
    parallels-iso: Size:       10350619
    parallels-iso: Compressed: 10448896
```

But it gets stuck there forever.  I was wondering if you had any pointers to please help me resolve.  I'd love to get this up and running on Parallels.

Thank you.
