### ISSUE TITLE
windows_2019.json vmware build No images available

### ISSUE THREAD

**Issue by basictheprogram** [StefanScherer/packer-windows#98]
First time trying to build insider build using windows_2019.json

I boot .iso via packer, Fusion comes up with this "No images are available".

```
packer build -only=vmware-iso -var 'disk_size=65536' --force  -var-file=/Users/tanner/.packer.d/my_windows_2019.json windows_2019.json
```
my_windows_2019.json contents
```yaml
{
    "iso_url": "/Users/tanner/Downloads/Windows_InsiderPreview_Server_17639.iso",
    "iso_checksum": "12cb8497a70234403c280adc1d79311fbcbb81e4",
    "iso_checksum_type": "sha1",
    "vhv_enable": "true",

    "winrm_timeout": "24h",
    "shutdown_timeout": "1h",
    "restart_timeout": "40h",
}
```
Packer has sat here for 4 hours
```
==> vmware-iso: Connecting to VM via VNC (127.0.0.1:5966)
==> vmware-iso: Typing the boot command over VNC...
==> vmware-iso: Waiting for WinRM to become available...
```
